### PR TITLE
Fix bugs in vector_distance

### LINKED ISSUE #275: Possible errors in vector_distance()
It seems that vector_distance function has couple of issues:
- It ignores the dimension parameter, and assumes that the input vectors have length of 3
- It performs square root operation two times: vector_norm() already takes a root.

### PR DESCRIPTION
**Pull request by ljbade**
Fixes #275

### CODE REVIEW

**Comment by ljbade** [comment]
Still needs unit tests

**Comment by ljbade** [comment]
Test cases added.

@swift-nav/firmware ready for review and merge

**Comment by benjamin0** [comment]
retest this please

File: src/linear_algebra.c [hunk 1]
```diff
@@ -983,7 +983,7 @@ void vector_cross(const double a[3], const double b[3],
 double vector_distance(u32 n, const double *a, const double *b) {
   double c[n];
   vector_subtract(n, a, b, c);
-  return sqrt(vector_norm(3, c));
+  return vector_norm(n, c);
```
Comment (akleeman) [inline src/linear_algebra.c]: Not sure how important performance is here, but we could compute the distance without creating the intermediary `c` vector (though it would involve near duplicate code).

**Comment by akleeman** [comment]
LGTM

**Comment by fnoble** [comment]
wow! nice catch
